### ISSUE TITLE
Resolve multilingualism

### ISSUE THREAD

**Issue by Primigenus** [Q42/CT-3000#24]
The readme and repo are in English but the tool and examples are in Dutch. That limits the appeal of the codebase. What would the impact be of offering an English translation?

**Comment by guidobouman** [comment]
Not that big actually. The whole editor language is generated based on a json file, so we could dynamically swap that out.

As far as the rest: in the source the objects are dutch, so that's a bit awkward is we would like to welcome PR's from international developers.

**Comment by guidobouman** [comment]
Language config:  
https://github.com/Q42/CT-3000/blob/master/src/config/language.json

Objects:  
https://github.com/Q42/CT-3000/tree/master/src/components/editor/objects

**Comment by lukasvan3l** [comment]
definitely, would like a language switch! But that's pretty nasty because to translate you'd need to take apart filenames (weer-goed.png) and variable names (weather = good). But yeah, definitely want this!

**Comment by fknipp** [comment]
@guidobouman The parser component also contains Dutch strings:

https://github.com/Q42/CT-3000/blob/master/src/classes/parser.js

**Comment by guidobouman** [comment]
Ah, true! That should be part of the language config, if you ask me.

**Comment by lukasvan3l** [comment]
Working on it in this branch: https://github.com/Q42/CT-3000/tree/feature/translations

It works for NL and EN, just change the language in `/config/config.js`. 
It uses a reflux store where it maps words in the chosen language document to the original dutch ones, based on the order of the items in the `/config/language-*.json` files.

Still some work to do:

- [ ]  Add chapter in README that tells how to translate
- [ ]  Have language setting get read from URL
- [ ]  Make language toggle in the UI

**Comment by fknipp** [comment]
While doing translations for German in this branch, I've found the following issues regarding the digiboard:

- The digiboard works only for NL (almost) completely.
- In EN: The name cannot be set, messages cannot be sent.
- In DE: There's no connection to the digibord at all, the digiboard shows always _0 gebruiker_.
- In all languages: Regardless of the selected music, the digiboard always shows _Geen muziek geselecteerd_, when I switch on the music as user.

**Comment by lukasvan3l** [comment]
Cool, just finished my own TODO's, and worked to translate the digiboard part of the app.

@fknipp could you add the DE translations for the digiboard? They're marked TODO in https://github.com/Q42/CT-3000/blob/feature/translations/src/config/language-de.json

I haven't looked at the functionality of the digiboard in different languages, will get to that next, but that should be the last part of this feature :)

**Comment by fknipp** [comment]
Cool, I've just set the German translations.

**Comment by guidobouman** [comment]
Nice work gentlemen!
