### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by fknipp** [Q42/CT-3000#26]
I've an almost clean node environment. 

For proper installation, I had to do two additional steps:
- `npm install -s autoprefixer`
- `cd node_modules; ln -s react-codemirror/node_modules/codemirror .`

I could provide a PR for adding the autoprefixer.

What's the best way to address the second issue?

**Comment by lukasvan3l** [comment]
hmm that's weird because `autoprefixer` is included in `css-loader`, which is in de devDependencies. Also, the `-s` param should add it to `package.json`, which it doesn't, probably because it's loaded in `css-loader`. What was the issue that you needed to install autoprefixer?

and on the second step: what is the issue you're encountering? On my mac it's working fine...

**Comment by fknipp** [comment]
My environment: Linux Mint 17.2, npm version 3.9.5, node version v6.2.2.

## autoprefixer

Without installing it, I see the following error message on **npm start**

```
> webpack-dev-server --progress --colors --hot --inline --host 0.0.0.0 --port 8000

module.js:442
    throw err;
    ^

Error: Cannot find module 'autoprefixer'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/knipp/workspace/CT-3000/webpack.config.js:2:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

I cannot find **autoprefixer** as dependency in _node_modules/css-loader/package.json_.

## codemirror

Without the symbolic link, **npm start** shows:

```
ERROR in ./src/components/editor/editorPane.js
Module not found: Error: Cannot resolve module 'codemirror/addon/mode/simple' in /home/knipp/workspace/CT-3000/src/components/editor
 @ ./src/components/editor/editorPane.js 33:0-39

ERROR in ./src/components/editor/editorPane.js
Module not found: Error: Cannot resolve module 'codemirror/addon/selection/active-line' in /home/knipp/workspace/CT-3000/src/components/editor
 @ ./src/components/editor/editorPane.js 35:0-49

ERROR in ./src/components/editor/editorPane.js
Module not found: Error: Cannot resolve module 'codemirror' in /home/knipp/workspace/CT-3000/src/components/editor
 @ ./src/components/editor/editorPane.js 25:18-39

ERROR in ./~/css-loader!./~/postcss-loader!./~/less-loader!./src/assets/style/main.less
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../node_modules/codemirror/lib/codemirror.css in /home/knipp/workspace/CT-3000/src/assets/style
 @ ./~/css-loader!./~/postcss-loader!./~/less-loader!./src/assets/style/main.less 3:10-118

ERROR in ./~/css-loader!./~/postcss-loader!./~/less-loader!./src/assets/style/main.less
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../node_modules/codemirror/theme/monokai.css in /home/knipp/workspace/CT-3000/src/assets/style
 @ ./~/css-loader!./~/postcss-loader!./~/less-loader!./src/assets/style/main.less 4:10-117
```

And the application does not work in the browser and shows these errors in the console.


Neither autoprefixer nor codemirror is installed globally on my system.

**Comment by lukasvan3l** [comment]
@fknipp I've updated all dependencies, and it still works like charm on my machine. Can you doublecheck if it works on your end? I'd like to close this issue :)

**Comment by fknipp** [comment]
Sorry for answering late, I've been busy organizing and doing two coding weeks for kids.

I've installed the CT-3000 according to the instruction with latest Node, and it worked – on the Linux notebook as well as on the MacBook.

So, I'll close the issue.

**Comment by lukasvan3l** [comment]
whoeii!! :)
